language: android
jdk: oraclejdk8
sudo: required

install: ./gradlew assemble
script: ./gradlew check
   
env:
  global:
    - ANDROID_API_LEVEL=23
    - EMULATOR_API_LEVEL=21
    - ANDROID_BUILD_TOOLS_VERSION=23.0.2
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TRAVIS=1


cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
