language: android
jdk: oraclejdk8
sudo: required

before_install:
- chmod +x gradlew

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - sys-img-armeabi-v7a-google_apis-23
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
