
language: android
jdk: oraclejdk8
# Use the Travis Container-Based Infrastructure
sudo: false

android:
  components:
    - tools
    - platform-tools
    - android-23
    - build-tools-24.0.0
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - sys-img-armeabi-v7a-android-23

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    
notifications:
  email: false
  
before_install:
  - chmod +x gradlew


script: 
  - ./gradlew build anyOtherGradleTask
