language: android
jdk: oraclejdk8
# Use the Travis Container-Based Infrastructure
sudo: required

before_install:
- chmod +x gradlew

env:
  global:
    # - ANDROID_TARGET=android-22
    # - ANDROID_ABI=armeabi-v7a
    - ANDROID_API_LEVEL=23
    - EMULATOR_API_LEVEL=26
    - ANDROID_BUILD_TOOLS_VERSION=26.0.2
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)
android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    # Specify both versions to resolve issue with missing image from google repository
    - android-$ANDROID_API_LEVEL
    - android-$EMULATOR_API_LEVEL
    - build-tools-23.0.2
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    # Image 23 might be missing from google repository
    - sys-img-armeabi-v7a-google_apis-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-google_apis-$EMULATOR_API_LEVEL
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - ./gradlew connectedAndroidTest coveralls
