
language: android
jdk: oraclejdk8
# Use the Travis Container-Based Infrastructure
sudo: required

before_install:
- chmod +x gradlew

android:
  components:
    - tools
    - platform-tools
    - android-23
    - android-26
    - build-tools-26.0.2
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - sys-img-armeabi-v7a-android-23
    - sys-img-armeabi-v7a-android-26
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
notifications:
  email: false
  
  script:
  - ./gradlew connectedAndroidTest coveralls
